FROM azure-powershell:alpine-3.13

ARG REPOSITORY=PSGallery
ARG MODULE=Az
ARG CONFIG=config
ARG AZURERM_CONTEXT_SETTINGS=AzureRmContextSettings.json
ARG AZURE=/root/.Azure
ARG VCS_REF="none"
ARG BUILD_DATE=
ARG VERSION=
ARG LATEST=
ARG BLOB_URL=
ARG IMAGE_NAME=mcr.microsoft.com/azure-powershell:${VERSION}-alpine-3.13

ENV AZUREPS_HOST_ENVIRONMENT="dockerImage/${VERSION}-alpine-3.13"

LABEL maintainer="Azure PowerShell Team <azdevxps@microsoft.com>" \
    readme.md="http://aka.ms/azpsdockerreadme" \
    description="This Dockerfile will install the latest release of Azure PowerShell." \
    org.label-schema.build-date=${BUILD_DATE} \
    org.label-schema.usage="http://aka.ms/azpsdocker" \
    org.label-schema.url="http://aka.ms/azpsdockerreadme" \
    org.label-schema.vcs-url="https://github.com/Azure/azure-powershell" \
    org.label-schema.name="azure powershell" \
    org.label-schema.vendor="Azure PowerShell" \
    org.label-schema.version=${VERSION} \
    org.label-schema.schema-version="1.0" \
    org.label-schema.vcs-ref=${VCS_REF} \
    org.label-schema.docker.cmd="docker run --rm ${IMAGE_NAME} pwsh -c '\$PSVERSIONTABLE'" \
    org.label-schema.docker.cmd.devel="docker run -it --rm -e 'DebugPreference=Continue' ${IMAGE_NAME} pwsh" \
    org.label-schema.docker.cmd.test="currently not available" \
    org.label-schema.docker.cmd.help="docker run --rm ${IMAGE_NAME} pwsh -c Get-Help"

RUN if [ "${LATEST}" = True ] ; then \
        # install latest azure-powershell from BLOB
        pwsh -Command Invoke-WebRequest -uri ${BLOB_URL} -OutFile latest.tar.gz && \       
        mkdir latest  && \
        tar -zxvf ./latest.tar.gz -C ./latest  && \
        pwsh -Command ./latest/InstallModule.ps1 -Scope AllUsers ;\
    else \
        # install old azure-powershell from PSGallery
        pwsh -Command Set-PSRepository -Name ${REPOSITORY} -InstallationPolicy Trusted && \
        pwsh -Command Install-Module -Name ${MODULE} -RequiredVersion ${VERSION} -Scope AllUsers -Repository ${REPOSITORY} && \
        pwsh -Command Set-PSRepository -Name ${REPOSITORY} -InstallationPolicy Untrusted ;\
    fi

# create AzureRmContextSettings.json before it was generated
COPY ${CONFIG}/${AZURERM_CONTEXT_SETTINGS} ${AZURE}/${AZURERM_CONTEXT_SETTINGS}
# ENV DOCKER_USERNAME=admin \
#     DOCKER_PWD=PASSWORD

# RUN sudo apk add --no-cache \
#     ca-certificates \
#     less \
#     ncurses-terminfo-base \
#     krb5-libs \
#     libgcc \
#     libintl \
#     libssl1.1 \
#     libstdc++ \
#     tzdata \
#     userspace-rcu \
#     zlib \
#     icu-libs \
#     curl

# RUN sudo apk -X https://dl-cdn.alpinelinux.org/alpine/edge/main add --no-cache lttng-ust

# RUN sudo mkdir -p /opt/microsoft/powershell/7

# RUN sudo tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7

# RUN sudo chmod +x /opt/microsoft/powershell/7/pwsh

# RUN sudo ln -s /opt/microsoft/powershell/7/pwsh /usr/bin/pwsh

# RUN pwsh

# RUN curl -L https://github.com/PowerShell/PowerShell/releases/download/v7.0.0-preview.4/powershell-7.0.0-preview.4-linux-alpine-x64.tar.gz \
# 		-o /tmp/powershell.tar.gz && \
# 	mkdir -p /opt/microsoft/powershell/7-preview && \
# 	tar zxf /tmp/powershell.tar.gz -C /opt/microsoft/powershell/7-preview && \
# 	rm /tmp/powershell.tar.gz && \
# 	chmod +x /opt/microsoft/powershell/7-preview/pwsh && \
# 	ln -s /opt/microsoft/powershell/7-preview/pwsh /usr/bin/pwsh-preview
#
# ENTRYPOINT ["pwsh-preview"]
# ENTRYPOINT ["/entrypoint.sh"]
CMD [pwsh]